version: "3.5"

services:  
  portainer:
    image: portainer/portainer-ce:2.17.1-alpine
    container_name: portainer
    restart: always
    ports:
     - 9003:9000
    volumes:
    # os volumes /etc/timezone e /etc/localtime é um workarounds para que os containers docker fiquem no mesmo horário do servidor
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
     - /var/run/docker.sock:/var/run/docker.sock
     - /var/lib/docker/volumes:/var/lib/docker/volumes
     - portainer_data:/data
    
volumes:
  portainer_data:
